/*
  _____ _ _ _                    _             _       
 |  ___(_) | |_ ___ _ __   _ __ | |_   _  __ _(_)_ __  
 | |_  | | | __/ _ \ '__| | '_ \| | | | |/ _` | | '_ \ 
 |  _| | | | ||  __/ |    | |_) | | |_| | (_| | | | | |
 |_|   |_|_|\__\___|_|    | .__/|_|\__,_|\__, |_|_| |_|
                          |_|            |___/         
# A Template for Wind_agentPlugin, a Filter Plugin
# Generated by the command: plugin -t filter -d wind_agent wind_agent
# Hostname: novo
# Current working directory: /home/leo/Desktop/Workspace/fontanelz
# Creation date: 2026-03-12T11:43:49.756+0100
# NOTICE: MADS Version 2.0.0
*/
// Mandatory included headers
#include <filter.hpp>
#include <nlohmann/json.hpp>
#include <pugg/Kernel.h>

// other includes as needed here
#include "negotiator.hpp"
#include "windekf.hpp"
#include "forecast.hpp"
#include <chrono>
#include <iostream>
#include <random>

// Define the name of the plugin
#ifndef PLUGIN_NAME
#define PLUGIN_NAME "wind_agent"
#endif

#define PERIOD 0.1

// Load the namespaces
using namespace std;
using json = nlohmann::json;
using namespace Eigen;
using namespace chrono;

// Plugin class. This shall be the only part that needs to be modified,
// implementing the actual functionality
class Wind_agentPlugin : public Filter<json, json> {

public:

/*
  Wind_agentPlugin() : 
    _input_power(0.0), 
    _output_power(0.0), 
    _covariance(0.01),
    _negotiator(_covariance, _input_power),
    _ekf(50, 3.46, 4),
    _gen(_rd()), _dis(-0.01, 0.01)
  { cout << "constructòr" << endl; }*/

  
  // Typically, no need to change this
  string kind() override { return PLUGIN_NAME; }

  // Implement the actual functionality here
  // Return types:
  // return_type::success: processing is valid, go to process
  // return_type::retry: skip processing go to next loop
  // return_type::warning: content of _error is tracked with register_event
  // return_type::error: _error is traced, skip process
  // return_type::critical: execution stops
  return_type load_data(json const &input, string topic = "", vector<unsigned char> const *blob = nullptr) override {

    // Do something with the input data
    
    if(topic == "forecast"){

      auto now_time_t = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now());
      tm* local_tm = std::localtime(&now_time_t);
      int current_hour = local_tm->tm_hour - 1;

      auto winds = input.at("wind");

      _wind = winds.at(current_hour).get<double>();
      _wind = _wind / 3.6;
      double next_wind = winds.at(++current_hour).get<double>();
      next_wind = next_wind / 3.6;

      _next_p_mean = (3.46 * pow(_wind, 3) + 3.46 * pow(next_wind, 3)) / 2; 

      future_power(input);
    }

    _negotiator.listen(input, topic);

    if(topic.rfind("omega", 0) == 0){

      _omega = input.at("output").at("omega").get<double>();
    }
    
    return return_type::success;
  }

  // We calculate the average of the last N values for each key and store it
  // into the output json object
  // Return types:
  // return_type::success: result is published
  // return_type::retry: don't publish, go to next loop
  // return_type::warning: content of _error is added to result befor publishing
  // return_type::error: _error is traced via register_event, don't publish
  // return_type::critical: execution stops
  return_type process(json &out, vector<unsigned char> *blob = nullptr) override {
    out.clear();
    
    auto now = steady_clock::now();
    duration<double> elapsed = now - _last_time;
    _last_time = now;
    _time_accumulator += elapsed.count();

    while(_time_accumulator >= PERIOD){

      _negotiator.set_weather_mean(_next_p_mean);

      _ekf.set_inputs(_wind, _output_power);
      _ekf.predict(PERIOD);

      VectorXd z(1); 
      z(0) = _omega;

      double tot_erg_w = max(0.8, _negotiator.get_ergodic_penalty() * _negotiator.get_weather_penalty());
      _ekf.update(z, tot_erg_w);

      _input_power = _ekf.get_state()(1);
      _covariance = _ekf.get_covariance()(1, 1);

      _time_accumulator -= PERIOD;
      
      _negotiator.set_cov(_covariance);
      _negotiator.set_pmax(_input_power);

      _negotiator.update_proposal();
      if(_negotiator.get_stab_flag()){

        _output_power = _negotiator.get_proposed_power();

        // cout << "\rErogating [" << _output_power << "W] while generating [" << _input_power << "W] at omega:" << _omega << "\033[K" << endl;
      
      } else{

        cout << "\rNegotiation in progess  \033[K" << endl;
      }

      if(_omega > -0.1 && _omega < 0.1){

        _omega = 0.1;
      }

      out = _negotiator.speak();
      out["hourly"] = _power_vector;
      out["fmu_input"]["resisting_torque"] =  _input_power / _omega; // input_power because all sources output all the possible power
      out["fmu_input"]["actual_wind"] = _wind;

      cout << "\rErogating [" << _output_power << "W] while generating [" << _input_power << "W] at omega:" << _omega << " with RT: " << _output_power / _omega <<"\033[K" << endl;

      if (!_agent_id.empty()) out["agent_id"] = _agent_id;
      return return_type::success;
    }   

    
    // load the data as necessary and set the fields of the json out variable

    // This sets the agent_id field in the output json object, only when it is
    // not empty

    return return_type::retry;
  }
  
  void set_params(const json &params) override {
    // Call the parent class method to set the common parameters 
    // (e.g. agent_id, etc.)
    Filter::set_params(params);
    
    _noise = _dis(_gen);
    //_negotiator.set_required_power(10000);

    // provide sensible defaults for the parameters by setting e.g.
    _params["some_field"] = "default_value";
    // more here...

    // then merge the defaults with the actually provided parameters
    // params needs to be cast to json
    _params.merge_patch(params);
      
  }

  // Implement this method if you want to provide additional information
  map<string, string> info() override { 
    // return a map of strings with additional information about the plugin
    // it is used to print the information about the plugin when it is loaded
    // by the agent
    
    return {};
    
  };

private:
  // Define the fields that are used to store internal resources
  
  double _input_power = 0.0;
  double _output_power = 0.0;
  double _covariance = 0.01;
  Negotiator _negotiator = Negotiator(0.01, 0.0);
  WindEKF _ekf = WindEKF(50, 3.46, 4);
  double _wind = 0.0;
  WeatherData _weather;
  vector <double> _power_vector;
  double _next_p_mean = 0.0;
  
  void future_power(const json& forecast_json);
  steady_clock::time_point _last_time = steady_clock::now();
  double _time_accumulator = 0.0;

  std::random_device _rd;
  std::mt19937 _gen;
  std::uniform_real_distribution<double> _dis;
  double _noise = 0.0;
  double _omega = 5.0;
  
};


  void Wind_agentPlugin::future_power(const json& forecast_json){

    _power_vector.clear();

    if(!forecast_json.contains("wind")){
      cout << "No forecast data available" << endl;
      return;
    }

    for(int i =0; i<24; ++i){

      if(i>=static_cast<int>(forecast_json.at("wind").size())){
        break;
      }
      double wind_kmh = forecast_json.at("wind").at(i).get<double>();
      double wind_ms = wind_kmh / 3.6;
      double power ;

     

      if(wind_kmh> 5 && wind_kmh < 80){
         power = 3.46 * pow(wind_ms, 3);
      }

      else{
        power = 0.0;
      }

      _power_vector.push_back(power);

    }

  }
      












/*
  ____  _             _             _      _
 |  _ \| |_   _  __ _(_)_ __     __| |_ __(_)_   _____ _ __
 | |_) | | | | |/ _` | | '_ \   / _` | '__| \ \ / / _ \ '__|
 |  __/| | |_| | (_| | | | | | | (_| | |  | |\ V /  __/ |
 |_|   |_|\__,_|\__, |_|_| |_|  \__,_|_|  |_| \_/ \___|_|
                |___/
Enable the class as plugin
*/
INSTALL_FILTER_DRIVER(Wind_agentPlugin, json, json);


/*
                  _       
  _ __ ___   __ _(_)_ __  
 | '_ ` _ \ / _` | | '_ \ 
 | | | | | | (_| | | | | |
 |_| |_| |_|\__,_|_|_| |_|
                          
*/

int main(int argc, char const *argv[])
{
  Wind_agentPlugin plugin;
  json params;
  json input, output;

  // Set example values to params
  params["test"] = "value";

  // Set the parameters
  plugin.set_params(params);

  // Set input data
  input["data"] = {
    {"AX", 1},
    {"AY", 2},
    {"AZ", 3}
  };

  // Set input data
  plugin.load_data(input);
  cout << "Input: " << input.dump(2) << endl;

  // Process data
  plugin.process(output);
  cout << "Output: " << output.dump(2) << endl;


  return 0;
}

